spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://127.0.0.1:1433;database=Certification;sendStringParametersAsUnicode=true;responseBuffering=adaptive
    username: sa
    password: 123qwe
  second-datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://112.33.100.180:1433;database=ecology_tg;sendStringParametersAsUnicode=true;responseBuffering=adaptive
    username: sa
    password: Tiangong@2020