spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://172.16.5.188:1433;database=Certification;sendStringParametersAsUnicode=true;responseBuffering=adaptive
    username: sa
    password: server003
  second-datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://103.228.161.147:1433;database=ecology_tg;sendStringParametersAsUnicode=true;responseBuffering=adaptive
    username: sa
    password: Tiangong@2020